cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart"),
    path('success/', views.success, name="success"),
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from simple_multivendor_site.settings import MEDIA_ROOT, MEDIA_URL
from simple_multivendor_site.settings import DEBUG

from .views import Contact, Home

app_name = 'core'


urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('contact/', Contact.as_view(), name='contact'),

]

product/urls.py
from . import views
from django.urls import path



app_name = 'product'


urlpatterns = [
    path('search', views.search, name="search"),
    path('<slug:category_slug>/<slug:product_slug>/', views.product, name="product"),
    path('<slug:category_slug>/', views.category, name="category"),
    
    ]

simple_multivendor_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls.static import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('vendor/', include('vendor.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=255)
    subject = forms.CharField(max_length=255)
    email = forms.EmailField()
    message = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 5, 'cols': 10})
    )

    def __str__(self):
        return self.subject

core/views.py
from product.models import Product
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse
from django.views.generic import FormView, ListView

from .forms import ContactForm
from simple_multivendor_site.settings import CONTACT_EMAIL


class Contact(FormView):
    form_class = ContactForm
    template_name = "core/contact.html"

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']
        try:
            send_mail(subject, message, email, [CONTACT_EMAIL])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return super().form_valid(form)


class Home(ListView):
    model = Product
    queryset = Product.objects.all()[0:8]
    context_object_name = 'newest_products'
    template_name = "core/frontpage.html"

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{% block title %}{% endblock title %} | E-commerce</title>
		<link rel="stylesheet" href="{% static 'css/bulma.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	</head>
	<body>
		<nav class="navbar is-success is-transperant">
			<div class="navbar-brand">
				<a href="/" class="navbar-item is-uppercase">
					<strong>GO-PORTAL</strong>
				</a>
				<a
					role="button"
					class="navbar-burger"
					aria-label="menu"
					aria-expanded="false"
					data-target="main-navbar"
				>
					<span aria-hidden="true"></span>
					<span aria-hidden="true"></span>
					<span aria-hidden="true"></span>
				</a>
			</div>
			<div class="navbar-menu" id="main-navbar">
				<div class="navbar-start">
					<form action="{% url 'product:search' %}" method="get" class="navbar-item">
						<div class="field has-addons">
							<div class="control has-icons-left">
								<input
									type="search"
									name="query"
									class="input"
									placeholder="Search..."
								/>
								<span class="icon is-small is-left">
									<i class="fas fa-search is-left"></i>
								</span>
							</div>
							<div class="control">
								<button class="button">Search</button>
							</div>
						</div>
					</form>
				</div>
				<div class="navbar-end">
					{% for category in menu_categories %}
					<a href="{% url 'category' category.slug %}" class="navbar-item"
						>{{ category.title }}</a
					>
					{% endfor %}
					<a href="{% url 'core:contact' %}" class="navbar-item">Contact Us</a>
					<a href="{% url 'cart:cart' %}" class="navbar-item">
						<span class="icon"><i class="fas fa-shopping-cart"></i></span>
						<span class="icon-text">
							Cart {% if cart %}({{ cart|length }}){% endif %}
						</span>
					</a>
					</div>
                
                {% if request.user.is_authenticated %}

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link is-capitalized">
                    {{user.vendor.name}}
                    </a>

                    <div class="navbar-dropdown">
                    <a class="navbar-item" href="{% url 'vendor:vendor-admin' %}">
                        Profile
                    </a>
                    <a class="navbar-item" href="{% url 'vendor:edit-vendor' %}">
                        Update
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="{% url 'vendor:logout' %}">
                        Logout
                    </a>
                    </div>
                </div>
		
					{% else %}
				<div class="navbar-item">
						 <a class="button is-success" href="{% url 'vendor:login' %}">
                            Login
                        </a>
				    </div>
                </div>	
					{% endif %}
				</div>
			</div>
		</nav>
		<section class="section">
			<div class="container">{% block content %}{% endblock content %}</div>
		</section>
		<footer class="footer is-info">
		<div class="hero-body has-text-centered">
			<h3 class="title is-4">Gonzaga's Farmer Portal</h3>
			{% if request.user.is_authenticated %}
			<a href="{% url 'vendor:vendor-admin' %}">My Dashboard</a>
			{% else %}
				<h6 class="subtitle is-6">Become one of us! For more Info, Contact Us.</h6>
				<h6 class="subtitle is-6">(Only Farmer of Gonzaga can register.)</h6>
				<a class="tag is-success"  href="{% url 'core:contact' %}">Contact Us</a>
			{% endif %}
			<br />
			<a class="tag is-dark" href="{% url 'vendor:vendors' %}">View All Farmer</a>
		</footer>
		</div>
		<div>
			<script src="{% static 'js/all.min.js' %}"></script>
			{% block script %}{% endblock script %}
			<script src="{% static 'js/main.js' %}"></script>
		</div>
	</body>
</html>

templates/core/contact.html
{% extends 'core/base.html' %}{% load bulma_tags %}
<div>{% block title %}Contact{% endblock title %}</div>
<div>
	{% block content %}
	<h1 class="title">Contact Us</h1>
	<h2 class="subtitle">Message us to register or You can leave feedback!</h2>
	<form action="." method="post" id="file-js">
		{% csrf_token %} {% if form.non_field_errors %}
		<div class="notification is-danger">
			<button class="delete"></button>
			{{ form.non_field_errors }}
		</div>
		{% endif %} {% if form.errors %}
		<div class="notification is-danger">
			<button class="delete"></button>
			<ul>
				{% for field in form %}{% for error in field.errors %}
				<li><strong>{{ field.label }}: </strong>{{ error }}</li>
				{% endfor %}{% endfor %}
			</ul>
		</div>
		{% endif %} {{ form|bulma }}
		<div class="field">
			<div class="control">
				<button class="button is-success is-rounded">Submit</button>
			</div>
		</div>
	</form>
	{% endblock content %}
</div>

templates/core/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a href="https://appseed.us/admin-dashboards/django" 
                 class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a href="https://bit.ly/3fKQZaL" 
                 class="font-weight-bold ml-1" target="_blank"> &copy; Creative-Tim</a> 
                 - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </footer>

templates/core/frontpage.html
{% extends 'core/base.html' %}
<div>{% block title %}Welcome{% endblock title %}</div>
<div>
	{% block content %}
	<section class="hero is-success mb-6">
		<div class="hero-body has-text-centered">
			<p class="title mb-6">Welcome to Gonzaga's Farmer Portal</p>
			<p class="subtitle">Buy products from our Farmers.</p>
                        <h6 class="subtitle is-6">(This page is for testing only, The products in this page is not available, Thank you for understanding.)</h6>
		</div>
	</section>
	<div class="columns is-multiline mb-6">
		<div class="column is-12 has-text-centered mt-6 mb-6">
			<h2 class="is-size-3">Newest Products</h2>
		</div>
		{% for product in newest_products %} {% include 'product/parts/list_item.html' %}
		<br />
		{% endfor %}
	</div>
	{% endblock content %}
</div>

templates/core/search.html
{% extends 'base.html' %}
<div>{% block title %}Search{% endblock title %}</div>
<div>
	{% block content %}
	<div class="columns is-multiline mb-6">
		<div class="column is-12 has-text-centered mt-6 mb-6">
			<h2 class="is-size-3">Search</h2>
			<h3>Search term: "{{ query }}"</h3>
		</div>
		{% for product in products %}
		<hr />
		{% include 'products/list.html' %} {% endfor %}
	</div>
	{% endblock content %}
</div>